### ISSUE TITLE
要多大的显存？1070显卡8G不够用

### ISSUE THREAD

**Issue by lightenthrive** [alibaba-damo-academy/FunClip#21]
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by R1ckShi** [comment]
gpu推理测试的比较少，可以尝试下在funclipper/videoclipper.py 的37与41行的funasr_model.generate中添加一下batch_size_s=400再试一下
