### ISSUE TITLE
NameError: name 'ClusterBackend' is not defined

### ISSUE THREAD

**Issue by andywen0090** [alibaba-damo-academy/FunClip#22]
Traceback (most recent call last):
  File "D:\2 github\FunClip\funclipper\launch.py", line 7, in <module>
    funasr_model = AutoModel(model="iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch",
  File "C:\Users\whyuan\anaconda3\envs\py39\lib\site-packages\funasr\auto\auto_model.py", line 129, in __init__
    self.cb_model = ClusterBackend().to(kwargs["device"])
NameError: name 'ClusterBackend' is not defined

请问上述报错该如何解决呢？

**Comment by andywen0090** [comment]
解决了，发现好像切了python版本到更新就好了，python版本最好不要用3.9，用新一些。
如果不行from funasr.models.campplus.cluster_backend import ClusterBackend这样也可以。
零散有挺多问题，requirmenets需要增加modelscope，否则模型下载不了。
另外还需要install torchaudio，还需要install hdbscan，这个有依赖windows的windows 10 sdk和MSVC V143 x64/x86生成工具等。

**Comment by R1ckShi** [comment]
感谢反馈，modelscope已经添加到requirments，torch和torchaudio因为与环境、cuda等相关没有添加至requirments
funasr的相关报错在最新的funasr中应该已经修正
