### ISSUE TITLE
为何在执行launch.py时总是提示AttributeError: module 'gradio' has no attribute 'Blocks'导致部署不成功？这是缺少了什么部件吗？

### ISSUE THREAD

**Issue by maxpowerduncan** [alibaba-damo-academy/FunClip#26]
为何在执行launch.py时总是提示AttributeError: module 'gradio' has no attribute 'Blocks'导致部署不成功？这是缺少了什么部件吗？
自认为该装的依赖都已经装上了，环境是win11，请指教怎么解决

**Comment by LauraGPT** [comment]
pip install -U gradio

**Comment by maxpowerduncan** [comment]
已解决，谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhifu gao ***@***.***&gt;
发送时间: 2024年4月24日 13:39
收件人: alibaba-damo-academy/FunClip ***@***.***&gt;
抄送: maxpowerduncan ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [alibaba-damo-academy/FunClip] 为何在执行launch.py时总是提示AttributeError: module 'gradio' has no attribute 'Blocks'导致部署不成功？这是缺少了什么部件吗？ (Issue #26)





 
pip install -U gradio

**Comment by huiyang865** [comment]
你好，这个问题怎么解决的？我一直都有这个问题。
