### ISSUE TITLE
启动报错ClusterBackend is not defined

### ISSUE THREAD

**Issue by Error9ood** [alibaba-damo-academy/FunClip#31]
启动之后报错NameError: name 'ClusterBackend' is not defined

Traceback (most recent call last):
  File "C:\PyCharmProject\FunClip-main\funclip\launch.py", line 7, in <module>
    funasr_model = AutoModel(model="iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch",
  File "C:\Users\10379\AppData\Local\Programs\Python\Python310\lib\site-packages\funasr\auto\auto_model.py", line 138, in __init__
    self.cb_model = ClusterBackend().to(kwargs["device"])
NameError: name 'ClusterBackend' is not defined

**Comment by LauraGPT** [comment]
`pip install funasr==1.0.25`

**Comment by leavenotrace** [comment]
(base) bobzheng@Bobs-MacBook-Pro FunClip % pip install funasr==1.0.25 sklearn
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: funasr==1.0.25 in /opt/anaconda3/lib/python3.11/site-packages (1.0.25)
Collecting sklearn
  Using cached https://mirrors.aliyun.com/pypi/packages/46/1c/395a83ee7b2d2ad7a05b453872053d41449564477c81dc356f720b16eac4/sklearn-0.0.post12.tar.gz (2.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by leavenotrace** [comment]
pip install funasr==1.0.25 scikit-learn 
...
Requirement already satisfied: sympy in /opt/anaconda3/lib/python3.11/site-packages (from torch->openai-whisper->funasr==1.0.25) (1.12)
Requirement already satisfied: networkx in /opt/anaconda3/lib/python3.11/site-packages (from torch->openai-whisper->funasr==1.0.25) (3.1)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.11/site-packages (from torch->openai-whisper->funasr==1.0.25) (3.1.3)
Requirement already satisfied: fsspec in /opt/anaconda3/lib/python3.11/site-packages (from torch->openai-whisper->funasr==1.0.25) (2023.10.0)
Requirement already satisfied: regex>=2022.1.18 in /opt/anaconda3/lib/python3.11/site-packages (from tiktoken->openai-whisper->funasr==1.0.25) (2023.10.3)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.11/site-packages (from jinja2->torch->openai-whisper->funasr==1.0.25) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /opt/anaconda3/lib/python3.11/site-packages (from sympy->torch->openai-whisper->funasr==1.0.25) (1.3.0)
(base) bobzheng@Bobs-MacBook-Pro FunClip % python3 funclip/launch.py              
2024-05-08 08:32:10,092 - modelscope - INFO - PyTorch version 2.3.0 Found.
2024-05-08 08:32:10,092 - modelscope - INFO - Loading ast index from /Users/bobzheng/.cache/modelscope/ast_indexer
2024-05-08 08:32:10,114 - modelscope - INFO - Loading done! Current index file version is 1.14.0, with md5 b84e6dd4bc67ed4bbc318196f1d5760c and a total number of 976 components indexed
2024-05-08 08:32:10,643 - modelscope - INFO - Use user-specified model revision: v2.0.4
ckpt: /Users/bobzheng/.cache/modelscope/hub/iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/model.pt
2024-05-08 08:32:12,885 - modelscope - INFO - Use user-specified model revision: v2.0.4
ckpt: /Users/bobzheng/.cache/modelscope/hub/damo/speech_fsmn_vad_zh-cn-16k-common-pytorch/model.pt
2024-05-08 08:32:13,408 - modelscope - INFO - Use user-specified model revision: v2.0.4
ckpt: /Users/bobzheng/.cache/modelscope/hub/damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch/model.pt
2024-05-08 08:32:14,843 - modelscope - INFO - Use user-specified model revision: v2.0.2
ckpt: /Users/bobzheng/.cache/modelscope/hub/damo/speech_campplus_sv_zh-cn_16k-common/campplus_cn_common.bin
Traceback (most recent call last):
  File "/Users/bobzheng/Documents/code/ai/partner/gao/FunClip/funclip/launch.py", line 7, in <module>
    funasr_model = AutoModel(model="iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch",
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/funasr/auto/auto_model.py", line 138, in __init__
    self.cb_model = ClusterBackend().to(kwargs["device"])
                    ^^^^^^^^^^^^^^
NameError: name 'ClusterBackend' is not defined

**Comment by wanghuii1** [comment]
Ensure scikit-learn>=1.3.0. It can be upgraded by running "pip install -U scikit-learn".

**Comment by leavenotrace** [comment]
Thanks, it is OK
