### ISSUE TITLE
no module named funclip

### ISSUE THREAD

**Issue by Spr-Peach** [alibaba-damo-academy/FunClip#38]
(venv) C:\Users\namiachy\FunClip>python funclip/launch.py
Traceback (most recent call last):
  File "C:\Users\namiachy\FunClip\funclip\launch.py", line 9, in <module>
    from funclip.videoclipper import VideoClipper
ModuleNotFoundError: No module named 'funclip'

please help me。。。

**Comment by R1ckShi** [comment]
sorry for introducing a bug, fixed in the latest code :)

**Comment by Spr-Peach** [comment]
> sorry for introducing a bug, fixed in the latest code :)

I mean Wow~ What can I say? Now it's running pretty well! I appreciate your reply and modification promptly, It means a lot to me! Thanx~

**Comment by R1ckShi** [comment]
> > sorry for introducing a bug, fixed in the latest code :)
> 
> I mean Wow~ What can I say? Now it's running pretty well! I appreciate your reply and modification promptly, It means a lot to me! Thanx~

you are welcome and any suggestion or feedback is welcomed too
a star will be appreciated, thanks!
