### ISSUE TITLE
裁剪+字幕报错

### ISSUE THREAD

**Issue by wuye901126** [alibaba-damo-academy/FunClip#55]
裁剪+字幕报错
![1715917000933](https://github.com/alibaba-damo-academy/FunClip/assets/24641901/104fbc36-b393-4f3c-9fc4-1f008458b364)

**Comment by R1ckShi** [comment]
如果不加字幕没有问题的话，那么应该是windows环境下通过moviepy调用imagemagick的问题
可以参考disscusion中的相关方法
