### ISSUE TITLE
#可以分割多少个，超过6个就不行，还是文本限制了多少

### ISSUE THREAD

**Issue by talway** [alibaba-damo-academy/FunClip#60]
7 periods found in the audio: from 797.44 to 845.945, from 864.11 to 943.6700000000001, from 965.36 to 1011.5600000000001, from 1078.33 to 1138.8149999999998, from 1143.56 to 1198.8149999999998, from 1218.96 to 1373.4399999999998, from 1381.2 to 1398.6799999999998

字数
6976

**Comment by talway** [comment]
10 periods found in the audio: from 1860.23 to 1872.8999999999999, from 1888.58 to 1921.5149999999999, from 1992.05 to 2005.0049999999999, from 2011.72 to 2105.2, from 2107.2 to 2118.85, from 2122.95 to 2200.88, from 2224.41 to 2231.205, from 2249.76 to 2269.24, from 2314.0 to 2336.5299999999997, from 2345.85 to 2403.47

**Comment by talway** [comment]
没搞懂这个剪切有个成功，有的不行
用#l连接有个可以找到，有的找不到，不知道问题在哪里

是视频太长还是文本太长了
还是文字格式问题

**Comment by talway** [comment]
视频长度2小时，

**Comment by talway** [comment]
文本找不到提示这个
文本就是从大段里面复制过来，不知道为什么识别或查询不到
No period found in the audio, return raw speech. You may check the recognition result and try other destination text.

**Comment by R1ckShi** [comment]
没有你这边的测试用例只能帮你分析下原因，可以不使用#连接一条一条试一下
如果每个单独裁剪可以但是合并起来不行那就是bug，不过按说应该没有这个问题

如果有的单条文本复制出来找不到那可以试下取这个文本内部的不同部分试一下，看是不是有文本格式或者编码之类的问题

**Comment by talway** [comment]
大概分割了10多段，就有一个段落无法识别；

本次还在排查。在试试

不过我前几天遇到同样类似例子，是复制页面内容直接到查询窗，就可以了

我个人猜测复制不全或格式问题；

2小时输出文字，如何保证选择或复制时候格式一致性，你这边有好的方案吗？
